name: flavor_sample_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_flavorizr: ^2.1.3

flutter:
  uses-material-design: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
  flavors:
    development:
      app:
        name: "FlavorSample.dev"
      android:
        applicationId: "com.idonuntius.flavorsample.dev"
      ios:
        bundleId: "com.idonuntius.flavorsample.dev"
    production:
      app:
        name: "FlavorSample.prod"
      android:
        applicationId: "com.idonuntius.flavorsample"
      ios:
        bundleId: "com.idonuntius.flavorsample"
